In [218]:
import numpy as np
from scipy.signal import butter, lfilter
from scipy.io import loadmat
import pandas as pd
from sklearn.model_selection  import train_test_split
from mne.decoding import CSP
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

# View Data

In [219]:
mat  = loadmat("BCI/A01T.mat")

In [244]:
pd.DataFrame(mat['data'][0][3][0][0][0]) # signals

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,0.341797,0.244141,-3.222656,-7.861328,-6.152344,-4.833984,0.976562,-6.347656,-10.595703,-11.962891,...,-10.400391,-10.302734,-7.128906,-8.544922,-7.519531,-6.982422,-3.564453,10.253906,20.507812,5.859375
1,-6.347656,-7.958984,-10.498047,-15.332031,-9.179688,-9.667969,-4.394531,-13.916016,-17.187500,-17.968750,...,-14.746094,-12.060547,-9.277344,-11.767578,-10.546875,-9.716797,-7.324219,2.441406,7.812500,-4.882812
2,-1.806641,-7.177734,-8.154297,-10.644531,-4.785156,-5.126953,-0.292969,-10.888672,-12.841797,-13.916016,...,-9.619141,-8.984375,-5.419922,-7.666016,-6.005859,-5.761719,-1.904297,6.347656,13.671875,-0.488281
3,-9.570312,-11.767578,-15.527344,-15.771484,-13.525391,-9.863281,-8.105469,-15.039062,-20.849609,-19.677734,...,-15.039062,-13.525391,-11.376953,-11.376953,-10.937500,-11.523438,-6.738281,4.394531,12.695312,-1.953125
4,-12.939453,-14.697266,-17.480469,-21.777344,-16.943359,-16.259766,-4.052734,-15.087891,-20.117188,-23.388672,...,-17.578125,-17.333984,-15.136719,-12.402344,-13.916016,-15.136719,-12.500000,1.464844,4.882812,-5.371094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96730,15.722656,8.007812,10.986328,10.302734,13.574219,13.378906,3.466797,4.736328,8.105469,6.250000,...,5.712891,6.445312,6.054688,12.011719,9.472656,8.691406,18.554688,0.488281,54.199219,-2.929688
96731,5.078125,2.832031,1.464844,1.171875,1.855469,4.248047,1.367188,-0.048828,-2.636719,-2.832031,...,-2.392578,-2.539062,-2.441406,6.250000,2.441406,2.099609,14.208984,-8.789062,46.875000,-10.253906
96732,0.292969,0.048828,-3.076172,-2.343750,-4.052734,0.927734,-2.294922,-2.880859,-7.617188,-5.810547,...,-3.710938,-2.294922,-0.634766,7.421875,2.832031,4.687500,17.871094,-2.441406,45.898438,-4.394531
96733,-6.347656,-5.126953,-9.716797,-10.546875,-11.572266,-4.882812,-2.294922,-5.615234,-12.109375,-11.621094,...,-6.396484,-6.542969,-3.027344,4.980469,0.390625,2.978516,16.845703,-4.882812,38.574219,-4.394531
96734,-9.716797,-7.177734,-13.964844,-14.501953,-15.332031,-8.105469,-5.224609,-9.130859,-16.943359,-16.845703,...,-12.548828,-10.058594,-4.980469,-2.099609,-5.029297,0.195312,10.595703,-5.371094,39.550781,-10.742188

In [243]:
pd.DataFrame(mat['data'][0][3][0][0][1]) # trials

        0
0     251
1    2254
2    4172
3    6124
4    8132
5   10243
6   12160
7   14210
8   16141
9   18139
10  20045
11  21940
12  23912
13  25856
14  27823
15  29943
16  31951
17  34017
18  36053
19  38119
20  40189
21  42269
22  44181
23  46212
24  48165
25  50126
26  52230
27  54234
28  56209
29  58235
30  60306
31  62413
32  64505
33  66596
34  68639
35  70703
36  72723
37  74695
38  76658
39  78583
40  80664
41  82642
42  84632
43  86751
44  88657
45  90585
46  92699
47  94758

In [245]:
pd.DataFrame(mat['data'][0][3][0][0][2]) # labels

    0
0   4
1   3
2   2
3   1
4   1
5   2
6   3
7   4
8   2
9   3
10  1
11  1
12  1
13  4
14  2
15  2
16  1
17  1
18  3
19  1
20  2
21  4
22  4
23  3
24  1
25  4
26  4
27  2
28  4
29  4
30  2
31  1
32  2
33  3
34  3
35  3
36  4
37  3
38  1
39  4
40  2
41  3
42  2
43  3
44  4
45  2
46  3
47  1

# Preprocessing

In [221]:
# Band Pass Filter with low cut of 4 hz and high cut of 38 hz
# This choice is because of the fact that motor imagery features generally happen in alpha and beta band of EEG.
def butter_bandpass (lowcut, highcut, fs, order=6):
    nyq = 0.5 * fs
    low = lowcut / nyq
    high = highcut / nyq
    b, a = butter(order, [low, high], btype='band')
    return b, a


def butter_bandpass_filter (signal, lowcut, highcut, fs, order=6):
    b, a = butter_bandpass(lowcut, highcut, fs, order=order)
    y = lfilter(b, a, signal)
    return y


def Preprocessing(path):
    # load data
    mat  = loadmat(path)
    data = mat['data']
    
    finalResult_x = np.empty([1, 22, 1500-500]) # signals
    finalResult_y = np.empty([1])              # labels
    N  = data.shape[1]              # number of samples


    # iteration on motor imagery task sessions (left hand, right hand, feet, tongue)
    # iterative from 3 to 8 => 6 runs 
    # each run callect 48 trials
    # then 6*48 = 288 trials
    
    # The signals were obtained using 22 electrodes for EEG and 3 electrodes for EOG => 22+3 = 25 channel
    # each signal have 25 channel and number of signals is ~ 10000
    
    for j in range(3,N):
        samples = data[0][j][0][0][0] # whole signal of the session
        trials  = data[0][j][0][0][1] # indices of successive trials
        labels  = data[0][j][0][0][2] # labels of corresponding task

        # iteration on tasks in each session
        for i in range(48):
            
            # we interested on signals between trials so we store it in x variable 
            if i < 47:
                x = samples[trials[i,0]:trials[i+1,0]]
            else:
                x = samples[trials[i,0]:]
            
            # remove the last 3 channels (EOG) and transpose the matrix
            x = x[500: 1500, 0: -3].T

            # apply band pass filter
            x = butter_bandpass_filter(
                signal  = x,
                lowcut  = 4,
                highcut = 38,
                fs      = 250,
                order   = 6
            )
            
            # normalize
            x = (x - np.mean(x))/np.std(x)

            x = np.expand_dims(x, axis=0)
            y = np.array([labels[i,0]])

            finalResult_x = np.concatenate((finalResult_x, x),axis=0)
            finalResult_y = np.concatenate((finalResult_y, y),axis=0)

    return finalResult_x[1:], finalResult_y[1:] # first sample is empty

In [247]:
data, labels = Preprocessing('BCI/A03T.mat')
data_test, labels_test = Preprocessing('BCI/A03E.mat')

In [248]:
np.array(labels).shape

(288,)

In [249]:
# convert labels from list of float to list of int 
labels=[int(x) for x in labels]
labels_test=[int(x) for x in labels_test]
labels=np.array(labels)
labels_test=np.array(labels_test)

# Feature Extraction

In [250]:
csp =CSP(n_components=4)
csp.fit(data,labels)
data_csp= csp.transform(data)
data_test_csp  = csp.transform(data_test)

Computing rank from data with rank=None
    Using tolerance 5.7 (2.2e-16 eps * 22 dim * 1.2e+15  max singular value)
    Estimated rank (mag): 22
    MAG: rank 22 computed from 22 data channels with 0 projectors
Reducing data rank from 22 -> 22
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank=None
    Using tolerance 5.7 (2.2e-16 eps * 22 dim * 1.2e+15  max singular value)
    Estimated rank (mag): 22
    MAG: rank 22 computed from 22 data channels with 0 projectors
Reducing data rank from 22 -> 22
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank=None
    Using tolerance 5.7 (2.2e-16 eps * 22 dim * 1.2e+15  max singular value)
    Estimated rank (mag): 22
    MAG: rank 22 computed from 22 data channels with 0 projectors
Reducing data rank from 22 -> 22
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank=None
    Using tolerance 5.6 (2.2e-16 eps * 22 dim * 1.2e+15  max singular value)
    Estimated rank (mag): 22
    MAG: rank 22 computed from 22 data channels with 0 projectors
Reducing data rank from 22 -> 22
Estimating covariance using EMPIRICAL
Done.

In [251]:
pd.DataFrame(data_csp)

            0         1         2         3
0   -0.866244 -0.092516 -0.256326  0.008463
1   -0.794816  0.433852 -0.291713 -0.296271
2   -0.849735  0.662874  0.142273 -0.256622
3    1.189151 -0.369741  0.044693  0.477652
4   -1.062769  0.204757  0.236680 -0.261126
..        ...       ...       ...       ...
283 -0.661043 -1.021915 -0.607809 -0.496478
284 -0.405788  0.016609 -0.411228 -0.213835
285 -0.219675 -0.103804 -0.863526 -0.348800
286 -1.002767 -0.617101  0.221761 -0.112738
287 -0.798283 -0.446145 -0.772589 -0.896519

[288 rows x 4 columns]

# Split data

In [252]:
x_train,x_test ,y_train,y_test = train_test_split(data_csp,labels,test_size = 0.25 , random_state =42 , shuffle = True,stratify = labels )
x_train.shape,x_test.shape ,y_train.shape,y_test.shape

((216, 4), (72, 4), (216,), (72,))

# Classifiers

In [253]:
randomforest =RandomForestClassifier().fit(x_train,y_train)
y_te_random = randomforest.predict(x_test)

clf = svm.SVC().fit(x_train, y_train)
y_te_svm = clf.predict(x_test)

knn = KNeighborsClassifier(n_neighbors=3).fit(x_train, y_train)
knn_pred = knn.predict(x_test)

lm = linear_model.LogisticRegression(multi_class='ovr', solver='liblinear').fit(x_train, y_train)
lm_pred = lm.predict(x_test)

print("Random Forst =",accuracy_score(y_te_random,y_test)*100)
print("SVM =",accuracy_score(y_te_svm,y_test)*100)
print("KNN =",accuracy_score(knn_pred,y_test)*100)
print("Logistic Regression =",accuracy_score(lm_pred,y_test)*100)

Random Forst = 83.33333333333334
SVM = 77.77777777777779
KNN = 76.38888888888889
Logistic Regression = 77.77777777777779

In [254]:
print(classification_report(y_test,y_te_random))
print(classification_report(y_test,lm_pred))

              precision    recall  f1-score   support

           1       0.80      0.89      0.84        18
           2       0.88      0.83      0.86        18
           3       0.94      0.83      0.88        18
           4       0.74      0.78      0.76        18

    accuracy                           0.83        72
   macro avg       0.84      0.83      0.83        72
weighted avg       0.84      0.83      0.83        72

              precision    recall  f1-score   support

           1       0.88      0.83      0.86        18
           2       0.83      0.83      0.83        18
           3       0.79      0.83      0.81        18
           4       0.61      0.61      0.61        18

    accuracy                           0.78        72
   macro avg       0.78      0.78      0.78        72
weighted avg       0.78      0.78      0.78        72

In [255]:
data_test_csp.shape

(288, 4)

In [256]:
y_val_random = randomforest.predict(data_test_csp)
y_val_svm = clf.predict(data_test_csp)
knn_val_pred = knn.predict(data_test_csp)
lm_val_pred = lm.predict(data_test_csp)

print("Random Forst =",accuracy_score(y_val_random,labels_test)*100)
print("SVM =",accuracy_score(y_val_svm,labels_test)*100)
print("KNN =",accuracy_score(knn_val_pred,labels_test)*100)
print("Logistic Regression =",accuracy_score(lm_val_pred,labels_test)*100)

Random Forst = 68.40277777777779
SVM = 66.66666666666666
KNN = 62.15277777777778
Logistic Regression = 68.75

# Save model

In [261]:
import joblib

# save
#joblib.dump(randomforest, "models/my_random_forest.joblib")

['my_random_forest.joblib']

In [262]:

# load model
loaded_rf = joblib.load("models/my_random_forest.joblib")

y_val_random = randomforest.predict(data_test_csp)
print("Random Forst =",accuracy_score(y_val_random,labels_test)*100)

Random Forst = 68.40277777777779